Merge from private repo auto_redis

diff --git a/extern/hitmap/examples/Heat/check b/extern/hitmap/examples/Heat/check
--- a/extern/hitmap/examples/Heat/check
+++ b/extern/hitmap/examples/Heat/check
@@ -1,66 +1,124 @@
-#!/usr/bin/python
+#!/bin/bash
+#
+# Script for testing the correct results of parallel Hitmap and reference applications
+#
+# (c) 2015-2021 Arturo Gonzalez-Escribano
+#
 
-import re
-import subprocess
-import os.path
-import sys
+# 1. EXPERIMENT INFORMATION
+# 1.1. APP NAME AND DEFAULT EXECUTABLES LIST
+APP_NAME="Sparse matrices - Heat propagation"
+EXE_NAMES="heat"
 
-# Input files
-hbfiles = ["../graphs/cage4.rb","../graphs/commanche_dual.rb"]
-hbfile_solutions = [91.836735,1000.0]
-result_error = 0.1
+# 1.2. APP/EXPERIMENT SPECIFIC PARAMETERS
+ITERATIONS="100"
+PROCS="1 2 3 5 7 9 13"
+INPUTS_SOLUTIONS="../graphs/cage4.rb,91.836735 ../graphs/commanche_dual.rb,1000.000000"
 
-def check_program(program,parallel,nprocs,hbfile,hbfile_solution):
-
-	# Check the input file
-	if not os.path.exists(hbfile):
-		print "Error: input file not found"
-		sys.exit(0)
-
-	# Message
-	print "Checking:" , program, hbfile
-	print "------------------------"
-
-	if not os.path.exists(program):
-		print "Error: Program not found"
-		sys.exit(0)
-
-	# Loop for the processes
-	for p in nprocs:
-
-		# Create the execution line
-		exelist = []
-		if parallel:
-			exelist = ["mpiexec"]
-			exelist.append("-n")
-			exelist.append(str(p))
-		exelist.append("./" + program)
-		exelist.append(hbfile)
-
-		# Execute the program
-		success = False
-		subp = subprocess.Popen(exelist, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
-		for line in subp.stdout.readlines():
-			result = re.search('Result: ([0-9\.]+)',line)
-			if result:
-				norm = float(result.group(1))
-				error = abs(norm-hbfile_solution)
-				if error < result_error:
-					success = True
-		retval = subp.wait()
+# 1.3. MPI RUN COMMAND
+if [ -z "$MPI_RUN" ]
+then
+	MPI_RUN="mpirun "
+fi
 
 
-		# Print the message
-		print "[Procs " + str(p).rjust(2) + "] ",
-		if success:
-			print "Ok"
-		else:
-			print "WRONG !!!"
+# 2. WRITE HEADER
+echo
+echo TESTING SCRIPT
+echo --------------
+echo "APPLICATION: $APP_NAME"
 
-	print
+# 3. CHECK PARAMETERS
+# 3.1. HELP
+if [ $# -lt 1 ]
+then
+	echo
+	echo -e "\tUsage: $0 all | <executable_names>"
+	echo
+	exit 1
+fi
 
+# 3.2. TEST SPECIFIC EXECUTABLES INSTEAD OF THE PREDEFINED LIST
+if [ $1 != all ]
+then
+	EXE_NAMES=$@
+fi
+echo "EXECUTABLES: $EXE_NAMES"
+echo
 
+# 3.3. CHECK THAT EXECUTABLES HAVE BEEN GENERATED
+for name in $EXE_NAMES
+do
+	OK=y
+	if [ ! -x $name ]
+	then
+		echo "Error: Executable not found -- $name"
+		OK=n
+	fi
+done
+if [ $OK != y ]
+then
+	echo
+	echo -e "\tBefore using this script generate the executables with:  $ make"
+	echo
+	exit 1
+fi
 
+# 4. TESTING EXPERIMENT
+function doTest() {
+	echo -e -n "Test $2 $3 $4:\t"
 
-for i in range(len(hbfiles)):
-	check_program("heat",True,[1,2,3,5,7,9,13],hbfiles[i],hbfile_solutions[i])
+	# EXECUTE PROGRAM
+	$MPI_RUN -n $2 ./$1 -i $3 $4 >check.output 2>check.err
+
+	# EXECUTION ERRORS, SKIP TESTING RESULT FILE
+	if [ 0 != $? ]
+	then
+			echo ERROR EXECUTING: $(cat check.err)
+			continue
+	fi
+
+	# IF THE RESULTS FILE HAS NOT BEEN GENERATED
+	OUTPUT=$(grep "Result: " check.output)
+	if [ "$OUTPUT" = "" ]
+	then
+		echo "Error: The executable \"$exe\" does not provide the expected output format"
+		echo "Output: "
+		cat check.output
+		echo
+		exit -1
+	# CHECK THE CONTENTS OF THE RESULTS LINE
+	else
+		CHECK=${OUTPUT#*: }
+		if [ "$CHECK" != "$5" ]
+		then
+			echo ERROR: $CHECK, Expected: $5
+		else
+			echo OK
+		fi
+	fi
+}
+
+# 5. LOOPS FOR TESTS
+for exe in $EXE_NAMES
+do
+	echo
+	echo "Testing: $exe"
+	echo "------------------------"
+	for input_sol in $INPUTS_SOLUTIONS
+	do
+		input=${input_sol%,*}
+		solution=${input_sol#*,}
+
+		for iter in $ITERATIONS
+		do
+			for procs in $PROCS
+			do
+				doTest $exe $procs $iter $input $solution
+			done
+		done
+	done
+done
+
+# 6. CLEAN
+rm -f check.err check.output
diff --git a/extern/hitmap/examples/Mmult/check b/extern/hitmap/examples/Mmult/check
--- a/extern/hitmap/examples/Mmult/check
+++ b/extern/hitmap/examples/Mmult/check
@@ -1,73 +1,125 @@
-#!/usr/bin/python
+#!/bin/bash
+#
+# Script for testing the correct results of parallel Hitmap and reference applications
+#
+# (c) 2015-2021 Arturo Gonzalez-Escribano
+#
 
-import re
-import subprocess
-import os.path
-import sys
+# 1. EXPERIMENT INFORMATION
+# 1.1. APP NAME AND DEFAULT EXECUTABLES LIST
+APP_NAME="Sparse matrices - Matrix-Vector multiplication"
+EXE_NAMES="mmult_bit mmult_csr"
 
-# Input file
-hbfile = "../graphs/cage4.rb"
-hbfile_solution = 12.37
-result_error = 0.01
+# 1.2. APP/EXPERIMENT SPECIFIC PARAMETERS
+ITERATIONS="10"
+PROCS="1 2 3 5 7 9 10 13 25"
+INPUTS_SOLUTIONS="../graphs/commanche_dual.rb,361566.93"
+RESULT_FORMAT="Result norm:"
 
-
-# Check the input file
-if not os.path.exists(hbfile):
-	print "Error: input file not found"
-	sys.exit(0)
-
-
-def check_program(program,parallel,nprocs):
-
-	# Message
-	print "Checking:" , program
-	print "------------------------"
-
-	if not os.path.exists(program):
-		print "Error: Program not found"
-		sys.exit(0)
-
-	# Loop for the processes
-	for p in nprocs:
-	
-		# Create the execution line
-		exelist = []
-		if parallel:
-			exelist = ["mpiexec"]
-			exelist.append("-n")
-			exelist.append(str(p))
-		exelist.append("./"+program)
-		exelist.append("-n")
-		exelist.append(str(100))
-		exelist.append(hbfile)
-
-		# Execute the program
-		success = False
-		subp = subprocess.Popen(exelist, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
-		for line in subp.stdout.readlines():
-			result = re.search('# Result norm: ([0-9\.]+)',line)
-			if result:
-				norm = float(result.group(1))
-				error = abs(norm-hbfile_solution)
-				if error < result_error:
-					success = True
-		retval = subp.wait()
+# 1.3. MPI RUN COMMAND
+if [ -z "$MPI_RUN" ]
+then
+	MPI_RUN="mpirun "
+fi
 
 
-		# Print the message
-		print "[Procs " + str(p).rjust(2) + "] ",
-		if success:
-			print "Ok"
-		else:
-			print "WRONG !!!"
+# 2. WRITE HEADER
+echo
+echo TESTING SCRIPT
+echo --------------
+echo "APPLICATION: $APP_NAME"
 
-	print 
+# 3. CHECK PARAMETERS
+# 3.1. HELP
+if [ $# -lt 1 ]
+then
+	echo
+	echo -e "\tUsage: $0 all | <executable_names>"
+	echo
+	exit 1
+fi
 
+# 3.2. TEST SPECIFIC EXECUTABLES INSTEAD OF THE PREDEFINED LIST
+if [ $1 != all ]
+then
+	EXE_NAMES=$@
+fi
+echo "EXECUTABLES: $EXE_NAMES"
+echo
 
-check_program("mmult_bit",True,[1,2,3,5,7,9,10,13,25])
-check_program("mmult_csr",True,[1,2,3,5,7,9,10,13,25])
+# 3.3. CHECK THAT EXECUTABLES HAVE BEEN GENERATED
+for name in $EXE_NAMES
+do
+	OK=y
+	if [ ! -x $name ]
+	then
+		echo "Error: Executable not found -- $name"
+		OK=n
+	fi
+done
+if [ $OK != y ]
+then
+	echo
+	echo -e "\tBefore using this script generate the executables with:  $ make"
+	echo
+	exit 1
+fi
 
+# 4. TESTING EXPERIMENT
+function doTest() {
+	echo -e -n "Test $2 $3 $4:\t"
 
+	# EXECUTE PROGRAM
+	$MPI_RUN -n $2 ./$1 -n $3 $4 >check.output 2>check.err
 
+	# EXECUTION ERRORS, SKIP TESTING RESULT FILE
+	if [ 0 != $? ]
+	then
+			echo ERROR EXECUTING: $(cat check.err)
+			continue
+	fi
 
+	# IF THE RESULTS FILE HAS NOT BEEN GENERATED
+	OUTPUT=$(grep "$RESULT_FORMAT" check.output)
+	if [ "$OUTPUT" = "" ]
+	then
+		echo "Error: The executable \"$exe\" does not provide the expected output format"
+		echo "Output: "
+		cat check.output
+		echo
+		exit -1
+	# CHECK THE CONTENTS OF THE RESULTS LINE
+	else
+		CHECK=${OUTPUT#*: }
+		if [ "$CHECK" != "$5" ]
+		then
+			echo ERROR: $CHECK, Expected: $5
+		else
+			echo OK
+		fi
+	fi
+}
 
+# 5. LOOPS FOR TESTS
+for exe in $EXE_NAMES
+do
+	echo
+	echo "Testing: $exe"
+	echo "------------------------"
+	for input_sol in $INPUTS_SOLUTIONS
+	do
+		input=${input_sol%,*}
+		solution=${input_sol#*,}
+
+		for iter in $ITERATIONS
+		do
+			for procs in $PROCS
+			do
+				doTest $exe $procs $iter $input $solution
+			done
+		done
+	done
+done
+
+# 6. CLEAN
+rm -f check.err check.output
diff --git a/extern/hitmap/examples/NAS_MG/check b/extern/hitmap/examples/NAS_MG/check
--- a/extern/hitmap/examples/NAS_MG/check
+++ b/extern/hitmap/examples/NAS_MG/check
@@ -1,45 +1,114 @@
-#!/usr/bin/python
+#!/bin/bash
+#
+# Script for testing the correct results of parallel Hitmap and reference applications
+#
+# (c) 2015-2021 Arturo Gonzalez-Escribano
+#
 
-import re
-import subprocess
-import os.path
-import sys
+# 1. EXPERIMENT INFORMATION
+# 1.1. APP NAME AND DEFAULT EXECUTABLES LIST
+APP_NAME="NAS MG (Multigrid stencil)"
+EXE_NAMES="mg_classA"
 
-# Program and number of processes
-program = "mg_classA"
-nprocs = [1,2,4,8,16]
+# 1.2. APP/EXPERIMENT SPECIFIC PARAMETERS
+PROCS="1 2 4 8 16"
+RESULT_FORMAT="VERIFICATION "
 
-# Message
-print "Checking:", program
-print "------------------------"
-
-if not os.path.exists(program):
-	print "Error: Program not found"
-	sys.exit(0)
-
-
-# Loop for the processes
-for p in nprocs:
-
-	# Create the execution line
-	exelist = ["mpiexec"]
-	exelist.append("-n")
-	exelist.append(str(p))
-	exelist.append("./" + program)
+# 1.3. MPI RUN COMMAND
+if [ -z "$MPI_RUN" ]
+then
+	MPI_RUN="mpirun "
+fi
 
 
-	# Execute the program
-	success = False
-	subp = subprocess.Popen(exelist, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
-	for line in subp.stdout.readlines():
-		if re.search('VERIFICATION SUCCESSFUL',line):
-			success = True
-	retval = subp.wait()
+# 2. WRITE HEADER
+echo
+echo TESTING SCRIPT
+echo --------------
+echo "APPLICATION: $APP_NAME"
 
+# 3. CHECK PARAMETERS
+# 3.1. HELP
+if [ $# -lt 1 ]
+then
+	echo
+	echo -e "\tUsage: $0 all | <executable_names>"
+	echo
+	exit 1
+fi
 
-	# Print the message
-	print "[Procs " + str(p).rjust(2) + "] ",
-	if success:
-		print "Ok"
-	else:
-		print "WRONG !!!"
+# 3.2. TEST SPECIFIC EXECUTABLES INSTEAD OF THE PREDEFINED LIST
+if [ $1 != all ]
+then
+	EXE_NAMES=$@
+fi
+echo "EXECUTABLES: $EXE_NAMES"
+echo
+
+# 3.3. CHECK THAT EXECUTABLES HAVE BEEN GENERATED
+for name in $EXE_NAMES
+do
+	OK=y
+	if [ ! -x $name ]
+	then
+		echo "Error: Executable not found -- $name"
+		OK=n
+	fi
+done
+if [ $OK != y ]
+then
+	echo
+	echo -e "\tBefore using this script generate the executables with:  $ make"
+	echo
+	exit 1
+fi
+
+# 4. TESTING EXPERIMENT
+function doTest() {
+	echo -e -n "Test $2 $3:\t"
+
+	# EXECUTE PROGRAM
+	$MPI_RUN -n $2 ./$1 >check.output 2>check.err
+
+	# EXECUTION ERRORS, SKIP TESTING RESULT FILE
+	if [ 0 != $? ]
+	then
+			echo ERROR EXECUTING: $(cat check.err)
+			continue
+	fi
+
+	# IF THE RESULTS FILE HAS NOT BEEN GENERATED
+	OUTPUT=$(grep "$RESULT_FORMAT" check.output)
+	if [ "$OUTPUT" = "" ]
+	then
+		echo "Error: The executable \"$exe\" does not provide the expected output format"
+		echo "Output: "
+		cat check.output
+		echo
+		exit -1
+	# CHECK THE CONTENTS OF THE RESULTS LINE
+	else
+		CHECK=$(echo ${OUTPUT#* })
+		if [ "$CHECK" != "SUCCESSFUL" ]
+		then
+			echo ERROR: $CHECK, Expected: SUCCESSFUL
+		else
+			echo OK
+		fi
+	fi
+}
+
+# 5. LOOPS FOR TESTS
+for exe in $EXE_NAMES
+do
+	echo
+	echo "Testing: $exe"
+	echo "------------------------"
+	for procs in $PROCS
+	do
+		doTest $exe $procs
+	done
+done
+
+# 6. CLEAN
+rm -f check.err check.output
